name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build release .zip
        shell: bash
        run: |
          cd greenhouse
          export PATH=$(cygpath -u $JAVA_HOME_17_X64)/bin:$PATH
          GIF_FILES=$(cd src; find . -name \*.gif)
          javac -d bin --module-source-path greenhouse=src -m greenhouse
          for F in $GIF_FILES
          do
            cp src/$F bin/greenhouse/$F
          done
          jpackage -p bin -m greenhouse/greenhouse.ExperimentView --name Greenhouse --type app-image
          7z a Greenhouse.zip Greenhouse

      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Windows release
          path: greenhouse/Greenhouse.zip
          if-no-files-found: error

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build release .zip
        run: |
          cd greenhouse
          GIF_FILES=$(cd src; find . -name \*.gif)
          javac -d bin --module-source-path greenhouse=src -m greenhouse
          for F in $GIF_FILES
          do
            cp src/$F bin/greenhouse/$F
          done
          jpackage -p bin -m greenhouse/greenhouse.Main --name Greenhouse --type app-image
          gcc -o run-Greenhouse -no-pie run-Greenhouse.c
          cp run-Greenhouse Greenhouse
          tar cJf Greenhouse.txz Greenhouse

      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Linux release
          path: greenhouse/Greenhouse.txz
          if-no-files-found: error

  macos:
    runs-on: macos-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build release .zip
        shell: zsh {0}
        run: cd greenhouse; PATH=$JAVA_HOME_17_X64/bin:$PATH . ./build-macos.sh

      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: MacOS release
          path: greenhouse/Greenhouse-macos.zip
          if-no-files-found: error
